docker push mcarsonacn/hystrix-dashboard
docker push mcarsonacn/shopping-cart-service
docker push mcarsonacn/edge-service
docker push mcarsonacn/catalog-service
docker push mcarsonacn/online-store-web
docker push mcarsonacn/discovery-service
docker push mcarsonacn/config-service
docker push mcarsonacn/payment-service
docker push mcarsonacn/user-service
docker push mcarsonacn/account-service
docker push mcarsonacn/order-service
docker push mcarsonacn/inventory-service